### ISSUE TITLE
`composer require kayqq/cloud-front-purge` failes

### ISSUE THREAD

**Issue by dillonbailey** [kayqq/craft-cloudfront-purge#1]
Running `composer require kayqq/cloud-front-purge` produces the following error.

<img width="1635" alt="Screen Shot 2020-01-24 at 9 04 35 am" src="https://user-images.githubusercontent.com/1067872/73027954-95ec7f00-3e88-11ea-8145-effed4338b7b.png">

Installing via the Craft GUI appears to run o.k.!

**Comment by kayqq** [comment]
The correct command is actually 
`composer require kayqq/craft-cloudfront-purge` 
not 
`composer require kayqq/cloud-front-purge`

I have updated the README.md instructions, cheers.

**Comment by dillonbailey** [comment]
Nice! Thanks @kayqq
